# Generated by Django 3.1.2 on 2021-01-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Ingredient', models.CharField(max_length=300)),
                ('Diet', models.CharField(choices=[('vegetarian', 'vegetarian'), ('non vegetarian', 'non vegetarian')], max_length=20)),
                ('PrepTime', models.IntegerField()),
                ('CookTime', models.IntegerField()),
                ('Flavor', models.CharField(max_length=20)),
                ('Course', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('Region', models.CharField(max_length=30)),
            ],
        ),
    ]
